import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import dotenv from 'dotenv';
import User from './src/models/User';
import Product from './src/models/Product';
import Shipment from './src/models/Shipment';
import Franchise from './src/models/Franchise';
import Order from './src/models/Order';

dotenv.config();

const seedDatabase = async () => {
  try {
    const mongoUri = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/stylesphere';
    await mongoose.connect(mongoUri);
    console.log('Connected to MongoDB for OneStall Seeding...');

    // Clear existing collections
    await User.deleteMany({});
    await Product.deleteMany({});
    await Shipment.deleteMany({});
    await Franchise.deleteMany({});
    await Order.deleteMany({});
    console.log('Cleared existing collections.');

    // Seed Franchise Hubs
    const franchises = await Franchise.create([
      {
        centreName: 'OneStall Delhi Central Logistics Hub',
        centreCode: 'OS-HUB-DEL01',
        city: 'New Delhi',
        state: 'Delhi',
        address: 'Plot 42, Okhla Industrial Area Phase III, New Delhi',
        managerName: 'Vikram Malhotra',
        managerPhone: '+91 98111 22334',
        assignedPincodes: ['110001', '110002', '110003', '110020', '110025'],
        activeRidersCount: 14,
        todayBookings: 320,
        todayDelivered: 284,
        pendingDeliveries: 36,
        codCollectedToday: 84500,
        totalRevenue: 584000,
        franchiseMarginPercent: 15,
        pendingSettlementAmount: 87600,
        performanceScore: 98.4,
        status: 'ACTIVE',
      },
      {
        centreName: 'OneStall Mumbai Gateway Hub',
        centreCode: 'OS-HUB-BOM01',
        city: 'Mumbai',
        state: 'Maharashtra',
        address: 'Bldg 12, MIDC Industrial Area, Andheri East, Mumbai',
        managerName: 'Anil Deshmukh',
        managerPhone: '+91 98222 33445',
        assignedPincodes: ['400001', '400050', '400072', '400093'],
        activeRidersCount: 18,
        todayBookings: 410,
        todayDelivered: 385,
        pendingDeliveries: 25,
        codCollectedToday: 132300,
        totalRevenue: 945000,
        franchiseMarginPercent: 15,
        pendingSettlementAmount: 141750,
        performanceScore: 97.1,
        status: 'ACTIVE',
      },
      {
        centreName: 'OneStall Bengaluru Silicon Hub',
        centreCode: 'OS-HUB-BLR01',
        city: 'Bengaluru',
        state: 'Karnataka',
        address: 'Koramangala 4th Block, Hosur Road, Bengaluru',
        managerName: 'Suresh Reddy',
        managerPhone: '+91 98450 11223',
        assignedPincodes: ['560001', '560034', '560100', '560068'],
        activeRidersCount: 16,
        todayBookings: 380,
        todayDelivered: 350,
        pendingDeliveries: 30,
        codCollectedToday: 95000,
        totalRevenue: 712000,
        franchiseMarginPercent: 15,
        pendingSettlementAmount: 106800,
        performanceScore: 99.0,
        status: 'ACTIVE',
      },
    ]);
    console.log('Seeded 3 Franchise Centres.');

    // Seed Users with distinct roles
    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash('password123', salt);
    const hashedAdminPass = await bcrypt.hash('admin123', salt);

    const superAdmin = await User.create({
      name: 'Super Admin',
      email: 'admin@onestall.in',
      password: hashedAdminPass,
      role: 'super_admin',
      isAdmin: true,
      phone: '+91 99999 00001',
      businessName: 'OneStall HQ Central',
      walletBalance: 250000,
    });

    const sellerUser = await User.create({
      name: 'Appario & Cloudtail Retail',
      email: 'seller@onestall.in',
      password: hashedPassword,
      role: 'seller',
      isAdmin: false,
      phone: '+91 98888 11112',
      businessName: 'Appario Retail Private Limited',
      gstin: '07AAAAA0000A1Z5',
      kycStatus: 'verified',
      walletBalance: 142350,
    });

    const franchiseUser = await User.create({
      name: 'Vikram Malhotra (Delhi Hub)',
      email: 'franchise@onestall.in',
      password: hashedPassword,
      role: 'franchise',
      isAdmin: false,
      phone: '+91 98111 22334',
      assignedFranchiseId: franchises[0]._id,
      assignedPincodes: ['110001', '110002', '110020'],
      walletBalance: 87600,
    });

    const riderUser = await User.create({
      name: 'Rahul Sharma',
      email: 'rider@onestall.in',
      password: hashedPassword,
      role: 'rider',
      isAdmin: false,
      phone: '+91 98112 34567',
      assignedPincodes: ['110001', '110020'],
      vehicleNumber: 'DL 01 AB 4920',
      walletBalance: 4200,
    });

    const customerUser = await User.create({
      name: 'Ajay Sharma',
      email: 'customer@onestall.in',
      password: hashedPassword,
      role: 'customer',
      isAdmin: false,
      phone: '+91 98765 43210',
      walletBalance: 2500,
    });
    console.log('Seeded Users for all platform roles.');

    // 4. Seed Real Amazon & Flipkart Bestseller Products (Mobiles, Electronics, Food, Fashion, Kitchen)
    const products = await Product.create([
      // --- MOBILES & ELECTRONICS ---
      {
        name: 'Apple iPhone 16 Pro (128 GB) - Desert Titanium',
        brand: 'Apple',
        category: 'Electronics',
        subcategory: 'Smartphones',
        description: 'Titanium design with larger 6.3-inch Super Retina XDR display, Camera Control, 4K 120 fps Dolby Vision, and A18 Pro chip. FREE 2-Day Delivery by OneStall Cargo.',
        image: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=800&q=80',
        images: ['https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=800&q=80'],
        sku: 'OS-APL-IP16P',
        hsn: '8517',
        gstRate: 18,
        mrp: 129900,
        price: 119900,
        discount: 8,
        countInStock: 25,
        weight: 0.45,
        dimensions: { length: 18, width: 10, height: 4 },
        sizes: ['128 GB', '256 GB', '512 GB'],
        colors: ['Desert Titanium', 'Natural Titanium', 'Black Titanium'],
        tags: ['apple', 'iphone', 'smartphone', 'electronics', 'bestseller'],
        sellerId: sellerUser._id,
        sellerName: 'Appario Retail Private Limited',
        approvalStatus: 'approved',
        commissionRate: 10,
        rating: 4.8,
        numReviews: 2450,
        featured: true,
      },
      {
        name: 'Samsung Galaxy S24 Ultra 5G (Titanium Gray, 12GB, 256GB Storage)',
        brand: 'Samsung',
        category: 'Electronics',
        subcategory: 'Smartphones',
        description: 'Galaxy AI is here. Search like never before with Circle to Search, live translate calls, 200MP camera with Quad Telephoto system, and built-in S Pen.',
        image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=800&q=80',
        images: ['https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=800&q=80'],
        sku: 'OS-SAM-S24U',
        hsn: '8517',
        gstRate: 18,
        mrp: 134999,
        price: 109999,
        discount: 19,
        countInStock: 18,
        weight: 0.5,
        dimensions: { length: 18, width: 10, height: 5 },
        sizes: ['256 GB', '512 GB'],
        colors: ['Titanium Gray', 'Titanium Black'],
        tags: ['samsung', 'galaxy', 'ai', 'smartphone', 'deal'],
        sellerId: sellerUser._id,
        sellerName: 'Appario Retail Private Limited',
        approvalStatus: 'approved',
        commissionRate: 10,
        rating: 4.7,
        numReviews: 1820,
        featured: true,
      },
      {
        name: 'Sony WH-1000XM5 Wireless Industry Leading Active Noise Canceling Headphones',
        brand: 'Sony',
        category: 'Electronics',
        subcategory: 'Headphones',
        description: 'Two processors and 8 microphones for unprecedented noise cancellation. Exceptional sound quality with Hi-Res Audio, 30-hour battery life with quick charge.',
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
        images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80'],
        sku: 'OS-SNY-XM5',
        hsn: '8518',
        gstRate: 18,
        mrp: 34990,
        price: 26990,
        discount: 23,
        countInStock: 30,
        weight: 0.42,
        dimensions: { length: 24, width: 22, height: 8 },
        sizes: ['Standard'],
        colors: ['Silver', 'Black', 'Midnight Blue'],
        tags: ['sony', 'anc', 'headphones', 'audio', 'deal'],
        sellerId: sellerUser._id,
        sellerName: 'Appario Retail Private Limited',
        approvalStatus: 'approved',
        commissionRate: 10,
        rating: 4.9,
        numReviews: 3890,
        featured: true,
      },
      {
        name: 'Noise ColorFit Pulse 4 Smart Watch with 1.85" AMOLED Display',
        brand: 'Noise',
        category: 'Electronics',
        subcategory: 'Wearables',
        description: 'Advanced Bluetooth calling with Tru Sync, Functional Crown, Always On Display, 100+ Sports Modes, and 7-Day Battery Life. 2-Day Delivery.',
        image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
        images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80'],
        sku: 'OS-NOI-PULSE4',
        hsn: '8517',
        gstRate: 18,
        mrp: 4999,
        price: 1499,
        discount: 70,
        countInStock: 80,
        weight: 0.2,
        dimensions: { length: 12, width: 10, height: 6 },
        sizes: ['Free Size'],
        colors: ['Jet Black', 'Rose Gold', 'Silver Gray'],
        tags: ['noise', 'smartwatch', 'amoled', 'bestseller'],
        sellerId: sellerUser._id,
        sellerName: 'Appario Retail Private Limited',
        approvalStatus: 'approved',
        commissionRate: 10,
        rating: 4.4,
        numReviews: 5410,
        featured: false,
      },

      // --- COMPUTING, MOBILES & GADGETS ---
      {
        name: 'Apple MacBook Air 13" M3 Chip (16GB Unified Memory, 512GB SSD) - Space Grey',
        brand: 'Apple',
        category: 'Electronics',
        subcategory: 'Laptops',
        description: 'Supercharged by the next-generation M3 chip, the incredibly thin and fast MacBook Air breezes through work and play with up to 18 hours of battery life.',
        image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
        images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80'],
        sku: 'OS-APL-MBA13M3',
        hsn: '8471',
        gstRate: 18,
        mrp: 134900,
        price: 124900,
        discount: 7,
        countInStock: 20,
        weight: 1.24,
        dimensions: { length: 30, width: 21, height: 1.1 },
        sizes: ['16GB RAM / 512GB SSD'],
        colors: ['Space Grey', 'Midnight', 'Starlight'],
        tags: ['macbook', 'apple', 'laptop', 'm3', 'electronics', 'deal'],
        sellerId: sellerUser._id,
        sellerName: 'Appario Retail Private Limited',
        approvalStatus: 'approved',
        commissionRate: 8,
        rating: 4.9,
        numReviews: 1420,
        featured: true,
      },
      {
        name: 'OnePlus 12 5G (Silky Black, 16GB RAM, 512GB Storage)',
        brand: 'OnePlus',
        category: 'Electronics',
        subcategory: 'Smartphones',
        description: 'Snapdragon 8 Gen 3 Mobile Platform, 4th Gen Hasselblad Camera for Mobile, 5400 mAh Battery with 100W SUPERVOOC fast charging.',
        image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80',
        images: ['https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80'],
        sku: 'OS-OP-12BLK',
        hsn: '8517',
        gstRate: 18,
        mrp: 69999,
        price: 64999,
        discount: 7,
        countInStock: 35,
        weight: 0.48,
        dimensions: { length: 18, width: 10, height: 4 },
        sizes: ['16GB / 512GB'],
        colors: ['Silky Black', 'Flowy Emerald'],
        tags: ['oneplus', 'smartphone', '5g', 'electronics', 'bestseller'],
        sellerId: sellerUser._id,
        sellerName: 'Appario Retail Private Limited',
        approvalStatus: 'approved',
        commissionRate: 10,
        rating: 4.6,
        numReviews: 3290,
        featured: true,
      },
      {
        name: 'Apple AirPods Pro (2nd Generation) with MagSafe Case (USB-C)',
        brand: 'Apple',
        category: 'Electronics',
        subcategory: 'Audio',
        description: 'Up to 2x more Active Noise Cancellation, Adaptive Audio, Transparency mode, and Personalized Spatial Audio with dynamic head tracking.',
        image: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?auto=format&fit=crop&w=800&q=80',
        images: ['https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?auto=format&fit=crop&w=800&q=80'],
        sku: 'OS-APL-APP2',
        hsn: '8518',
        gstRate: 18,
        mrp: 24900,
        price: 20999,
        discount: 16,
        countInStock: 50,
        weight: 0.25,
        dimensions: { length: 10, width: 8, height: 4 },
        sizes: ['Universal Fit'],
        colors: ['White'],
        tags: ['airpods', 'apple', 'anc', 'earbuds', 'deal'],
        sellerId: sellerUser._id,
        sellerName: 'Appario Retail Private Limited',
        approvalStatus: 'approved',
        commissionRate: 10,
        rating: 4.8,
        numReviews: 5120,
        featured: true,
      },
      {
        name: 'Philips Series 7000 14-in-1 All-in-One Trimmer for Men',
        brand: 'Philips',
        category: 'Beauty',
        subcategory: 'Grooming',
        description: 'DualCut technology for maximum precision, 14 quality tools for styling face, hair and body, 120 minutes run time with showerproof stainless steel body.',
        image: 'https://images.unsplash.com/photo-1621607512214-68297480165e?auto=format&fit=crop&w=800&q=80',
        images: ['https://images.unsplash.com/photo-1621607512214-68297480165e?auto=format&fit=crop&w=800&q=80'],
        sku: 'OS-PHI-MG7715',
        hsn: '8510',
        gstRate: 18,
        mrp: 4995,
        price: 3499,
        discount: 30,
        countInStock: 60,
        weight: 0.55,
        dimensions: { length: 22, width: 14, height: 8 },
        sizes: ['14-in-1 Kit'],
        colors: ['Metallic Silver'],
        tags: ['philips', 'trimmer', 'grooming', 'men', 'bestseller'],
        sellerId: sellerUser._id,
        sellerName: 'Appario Retail Private Limited',
        approvalStatus: 'approved',
        commissionRate: 10,
        rating: 4.6,
        numReviews: 4890,
        featured: false,
      },
      {
        name: 'Ray-Ban Aviator Classic Green Sunglasses (Gold Metal Frame, 58mm)',
        brand: 'Ray-Ban',
        category: 'Fashion',
        subcategory: 'Eyewear',
        description: 'Originally designed for U.S. aviators in 1937, Ray-Ban Classic Aviator sunglasses combine iconic styling with exceptional quality and 100% UV protection.',
        image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80',
        images: ['https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80'],
        sku: 'OS-RAY-RB3025',
        hsn: '9004',
        gstRate: 18,
        mrp: 9890,
        price: 6990,
        discount: 29,
        countInStock: 30,
        weight: 0.3,
        dimensions: { length: 18, width: 8, height: 6 },
        sizes: ['58 mm'],
        colors: ['Arista Gold Frame / G-15 Green'],
        tags: ['rayban', 'sunglasses', 'aviator', 'fashion', 'luxury'],
        sellerId: sellerUser._id,
        sellerName: 'Appario Retail Private Limited',
        approvalStatus: 'approved',
        commissionRate: 10,
        rating: 4.7,
        numReviews: 1890,
        featured: true,
      },
      {
        name: 'JBL Flip 6 Wireless Portable Waterproof Bluetooth Speaker',
        brand: 'JBL',
        category: 'Electronics',
        subcategory: 'Speakers',
        description: 'Bold JBL Original Pro Sound with exceptional clarity, 2-way speaker system, IP67 waterproof and dustproof, 12 hours of playtime.',
        image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
        images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'],
        sku: 'OS-JBL-FLIP6',
        hsn: '8518',
        gstRate: 18,
        mrp: 13999,
        price: 8999,
        discount: 36,
        countInStock: 45,
        weight: 0.65,
        dimensions: { length: 20, width: 9, height: 9 },
        sizes: ['Standard'],
        colors: ['Squad Camo', 'Midnight Black', 'Ocean Blue'],
        tags: ['jbl', 'speaker', 'bluetooth', 'audio', 'deal'],
        sellerId: sellerUser._id,
        sellerName: 'Appario Retail Private Limited',
        approvalStatus: 'approved',
        commissionRate: 10,
        rating: 4.7,
        numReviews: 6240,
        featured: true,
      },
      {
        name: 'Dyson V8 Absolute Cordless Vacuum Cleaner with De-tangling Motorbar',
        brand: 'Dyson',
        category: 'Home & Kitchen',
        subcategory: 'Home Appliances',
        description: 'Powerful, versatile, and low noise. Engineered for homes with pets. Up to 40 minutes of fade-free power with 2 cleaner heads and 4 accessories.',
        image: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=800&q=80',
        images: ['https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=800&q=80'],
        sku: 'OS-DYS-V8ABS',
        hsn: '8508',
        gstRate: 18,
        mrp: 43900,
        price: 29900,
        discount: 32,
        countInStock: 15,
        weight: 2.6,
        dimensions: { length: 125, width: 25, height: 22 },
        sizes: ['V8 Absolute'],
        colors: ['Silver / Yellow'],
        tags: ['dyson', 'vacuum', 'home', 'appliances', 'premium'],
        sellerId: sellerUser._id,
        sellerName: 'Appario Retail Private Limited',
        approvalStatus: 'approved',
        commissionRate: 10,
        rating: 4.8,
        numReviews: 1670,
        featured: true,
      },

      // --- FASHION & LIFESTYLE ---
      {
        name: 'Nike Air Jordan 1 Low Retro Sneakers - White & University Blue',
        brand: 'Nike',
        category: 'Fashion',
        subcategory: 'Footwear',
        description: 'Inspired by the 1985 original, the Air Jordan 1 Low offers a clean, classic look that’s familiar yet always fresh. Encapsulated Air-Sole unit provides lightweight cushioning.',
        image: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=800&q=80',
        images: ['https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=800&q=80'],
        sku: 'OS-NIK-AJ1LOW',
        hsn: '6404',
        gstRate: 12,
        mrp: 11995,
        price: 8995,
        discount: 25,
        countInStock: 35,
        weight: 0.95,
        dimensions: { length: 32, width: 22, height: 12 },
        sizes: ['UK 7', 'UK 8', 'UK 9', 'UK 10'],
        colors: ['White & University Blue', 'Bred Toe'],
        tags: ['nike', 'jordan', 'sneakers', 'fashion', 'shoes', 'bestseller'],
        sellerId: sellerUser._id,
        sellerName: 'Appario Retail Private Limited',
        approvalStatus: 'approved',
        commissionRate: 10,
        rating: 4.8,
        numReviews: 1280,
        featured: true,
      },
      {
        name: "Levi's Men's 511 Slim Fit Stretchable Denim Jeans (Dark Indigo)",
        brand: "Levi's",
        category: 'Fashion',
        subcategory: 'Men Jeans',
        description: 'A modern slim with room to move. Added stretch for all-day comfort. Sits below the waist with a slim leg from hip to ankle.',
        image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80',
        images: ['https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80'],
        sku: 'OS-LEV-511IND',
        hsn: '6203',
        gstRate: 12,
        mrp: 3799,
        price: 1899,
        discount: 50,
        countInStock: 50,
        weight: 0.65,
        dimensions: { length: 34, width: 24, height: 5 },
        sizes: ['30', '32', '34', '36'],
        colors: ['Dark Indigo Wash', 'Light Stone Wash'],
        tags: ['levis', 'jeans', 'denim', 'fashion', 'men'],
        sellerId: sellerUser._id,
        sellerName: 'Appario Retail Private Limited',
        approvalStatus: 'approved',
        commissionRate: 10,
        rating: 4.6,
        numReviews: 2890,
        featured: false,
      },
      {
        name: "Puma Men's Softride Pro Walking & Running Shoes (Puma Black)",
        brand: 'Puma',
        category: 'Fashion',
        subcategory: 'Footwear',
        description: 'Engineered with SOFTRIDE foam technology for ultimate cushioning and effortless all-day comfort. Breathable knitted mesh upper with rubber traction outsole.',
        image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
        images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
        sku: 'OS-PUM-SOFTR',
        hsn: '6404',
        gstRate: 12,
        mrp: 4499,
        price: 2199,
        discount: 51,
        countInStock: 45,
        weight: 0.75,
        dimensions: { length: 30, width: 20, height: 12 },
        sizes: ['UK 7', 'UK 8', 'UK 9', 'UK 10'],
        colors: ['Puma Black-Red', 'High-Risk Red'],
        tags: ['puma', 'shoes', 'running', 'sports', 'deal'],
        sellerId: sellerUser._id,
        sellerName: 'Appario Retail Private Limited',
        approvalStatus: 'approved',
        commissionRate: 10,
        rating: 4.7,
        numReviews: 1940,
        featured: true,
      },

      // --- HOME & KITCHEN ---
      {
        name: 'Prestige Iris 750 Watt Mixer Grinder with 3 Stainless Steel Jars + 1 Juicer Jar',
        brand: 'Prestige',
        category: 'Home & Kitchen',
        subcategory: 'Kitchen Appliances',
        description: 'Heavy-duty 750W copper motor with overload protection, 3 multipurpose stainless steel jars, and a transparent juicer jar with blade for fruit juices and purees.',
        image: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=800&q=80',
        images: ['https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=800&q=80'],
        sku: 'OS-PRE-IRIS750',
        hsn: '8509',
        gstRate: 18,
        mrp: 4295,
        price: 2699,
        discount: 37,
        countInStock: 40,
        weight: 4.5,
        dimensions: { length: 38, width: 30, height: 26 },
        sizes: ['4 Jars (750W)'],
        colors: ['White & Blue'],
        tags: ['prestige', 'mixer', 'grinder', 'kitchen', 'home', 'bestseller'],
        sellerId: sellerUser._id,
        sellerName: 'Appario Retail Private Limited',
        approvalStatus: 'approved',
        commissionRate: 10,
        rating: 4.5,
        numReviews: 4560,
        featured: true,
      },
      {
        name: 'Pigeon by Stovekraft Non-Stick Aluminium 3-Piece Cookware Set',
        brand: 'Pigeon',
        category: 'Home & Kitchen',
        subcategory: 'Cookware',
        description: 'Contains Flat Tawa (25cm), Fry Pan (24cm) and Kadai with Glass Lid (24cm). 5-layer non-stick Greblon coating with cool-touch Bakelite handles.',
        image: 'https://images.unsplash.com/photo-1584990347449-399086a9a838?auto=format&fit=crop&w=800&q=80',
        images: ['https://images.unsplash.com/photo-1584990347449-399086a9a838?auto=format&fit=crop&w=800&q=80'],
        sku: 'OS-PIG-SET3',
        hsn: '7615',
        gstRate: 12,
        mrp: 2495,
        price: 1199,
        discount: 52,
        countInStock: 55,
        weight: 2.8,
        dimensions: { length: 36, width: 28, height: 16 },
        sizes: ['3 Piece Set'],
        colors: ['Granite Grey'],
        tags: ['pigeon', 'cookware', 'nonstick', 'kitchen', 'deal'],
        sellerId: sellerUser._id,
        sellerName: 'Appario Retail Private Limited',
        approvalStatus: 'approved',
        commissionRate: 10,
        rating: 4.4,
        numReviews: 3890,
        featured: false,
      },
    ]);
    console.log(`Seeded ${products.length} Real Amazon / Flipkart Bestseller Products!`);

    // Seed Active OneStall Cargo Shipments
    const activeAwb1 = 'OS-882910412';
    const activeOrder1 = await Order.create({
      user: customerUser._id,
      customerName: 'Ajay Sharma',
      customerEmail: 'customer@onestall.in',
      customerPhone: '+91 98765 43210',
      orderItems: [
        {
          product: products[0]._id,
          name: products[0].name,
          image: products[0].image,
          price: products[0].price,
          qty: 1,
          sellerId: sellerUser._id,
          sellerName: 'Appario Retail Private Limited',
          commissionRate: 10,
          category: 'Electronics',
        },
      ],
      shippingAddress: {
        street: 'Flat 402, Lotus Boulevard, Sector 100',
        city: 'New Delhi',
        state: 'Delhi',
        pincode: '110001',
      },
      paymentMethod: 'COD',
      itemsPrice: 119900,
      shippingPrice: 0,
      discountPrice: 0,
      totalPrice: 119900,
      isPaid: false,
      orderStatus: 'OUT_FOR_DELIVERY',
      awb: activeAwb1,
      courierPartner: 'OneStall Express',
      estimatedDeliveryDate: 'Today by 6:00 PM',
    });

    await Shipment.create({
      awb: activeAwb1,
      orderId: activeOrder1._id,
      orderNumber: 'ORD-910412',
      senderName: 'Appario Retail Private Limited',
      senderPhone: '+91 98888 11112',
      pickupAddress: 'Warehouse B3, Okhla Phase 2, New Delhi',
      pickupPincode: '110020',
      receiverName: 'Ajay Sharma',
      receiverPhone: '+91 98765 43210',
      deliveryAddress: 'Flat 402, Lotus Boulevard, Sector 100, New Delhi',
      deliveryPincode: '110001',
      packageType: 'High-Value Electronics Parcel',
      weight: 0.45,
      dimensions: { length: 18, width: 10, height: 4 },
      volumetricWeight: 0.5,
      declaredValue: 119900,
      paymentMode: 'COD',
      codAmount: 119900,
      courierPartner: 'OneStall Express',
      currentStatus: 'OUT_FOR_DELIVERY',
      assignedFranchise: 'OneStall Delhi Central Logistics Hub (OS-HUB-DEL01)',
      assignedRiderName: 'Rahul Sharma',
      assignedRiderPhone: '+91 98112 34567',
      deliveryOtp: '7492',
      gpsLocation: { lat: 28.6139, lng: 77.2090 },
      settlementStatus: 'PENDING',
      timeline: [
        {
          stage: 'BOOKING_CONFIRMED',
          statusText: 'Marketplace Order confirmed. OneStall Express AWB generated.',
          location: 'Delhi Central Hub (110020)',
          timestamp: new Date(Date.now() - 20 * 3600 * 1000),
          responsiblePerson: 'OneStall Fulfillment Dispatch Engine',
          notes: 'Auto-manifested with franchise hub.',
        },
        {
          stage: 'PICKED_UP',
          statusText: 'Package picked up from seller warehouse and weight verified.',
          location: 'Okhla Phase 2 Sorting Center',
          timestamp: new Date(Date.now() - 14 * 3600 * 1000),
          responsiblePerson: 'Amit Kumar (Pickup Agent)',
          notes: 'Weight verified: 0.45 kg. Security barcode seal attached.',
        },
        {
          stage: 'IN_TRANSIT',
          statusText: 'Dispatched via Express Corridor van DL-1L-4421 to local delivery franchise.',
          location: 'Delhi NCR Transit Corridor',
          timestamp: new Date(Date.now() - 6 * 3600 * 1000),
          responsiblePerson: 'Driver: Ramesh Yadav',
          notes: 'Transit run on-schedule.',
        },
        {
          stage: 'OUT_FOR_DELIVERY',
          statusText: 'Out for delivery with rider Rahul Sharma. Verification OTP sent to customer.',
          location: 'Connaught Place / Central Delhi Route',
          timestamp: new Date(Date.now() - 1 * 3600 * 1000),
          responsiblePerson: 'Rahul Sharma (Delivery Executive)',
          notes: 'COD collection pending: ₹1,19,900. Live GPS tracking active.',
        },
      ],
    });

    console.log('OneStall Amazon/Flipkart dataset seeded successfully!');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding data:', error);
    process.exit(1);
  }
};

seedDatabase();
